name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.1
        run: sudo xcode-select -s /Applications/Xcode_15.1.app
      - name: Resolve dependencies
        run: swift package resolve
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test
